version: "3.8"

services:
  db:
    container_name: db
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
    ports:
      - 5432:5432
    volumes:
      - ./database_data:/var/lib/postgresql/data
    networks:
      - transcendence

  back_end:
    container_name: back_end
    depends_on:
      - db
    image: back_end
    build:
      dockerfile: ./back_end/Dockerfile
    ports:
      - "3001:3001"
      - "5555:5555"
    volumes:
      - ./back_end/app/:/app/
    networks:
      - transcendence

  front_end:
    container_name: front_end
    depends_on:
      - db
    image: front_end
    build:
      dockerfile: ./front_end/Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./front_end/app:/app
    networks:
      - transcendence

networks:
  transcendence:
