openapi: 3.0.3
info:
  title: Trascendence
  description: Web project at CODAM school.
  version: 1.0.0

servers:
  - url: 'http://{host}:{port}'
    variables:
      host:
        default: localhost
      port:
        default: '8080'

paths:

  /players:
    post:
      tags:
        - player
      summary: Add player to the game.
      description: This allows you to add a single player.
      operationId: addPlayer

      requestBody:
        description: This is the player object.
        content:
          'application/json':
            schema:
              $ref: '#/components/schemas/player'

      responses:
        '201':
          description: The player has been created.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/player'
    get:
      tags:
        - player
      summary: Returns all the players.
      description: This allows get all players.
      operationId: getPlayers

      responses:
        '200':
          description: Successful list of players.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/players'


  /players/{playerId}:
    put:
      tags:
        - player
      summary: Update an existing player.
      description: This allows you to update a single player.
      operationId: updatePlayer
      parameters:
        - name: playerId
          in: path
          required: true
          schema:
            type: integer
            format: int64

      requestBody:
        description: This is the player object.
        content:
          'application/json':
            schema:
              $ref: '#/components/schemas/player'

      responses:
        '204':
          description: The player has been updated.

    get:
      tags:
        - player
      summary: Find player by id.
      description: This allows you to get a single player.
      operationId: getPlayerById
      parameters:
        - name: playerId
          in: path
          required: true
          schema:
            type: integer
            format: int64

      responses:
        '200':
          description: Successful return of player.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/player'

  /players/{playerId}/uploadAvatar:
    post:
      tags:
        - player
      summary: Upload a player avatar.
      description: This allows to upload an image avatar for the player.
      operationId: uploadAvatar
      parameters:
        - name: playerId
          in: path
          description: ID of player to update
          required: true
          schema:
            type: integer
            format: int64

      requestBody:
        content:
          application/octet-stream:
            schema:
              type: string
              format: binary

      responses:
        '204':
          description: The image has been upload.


  /players/{playerId}/friends:
    post:
      tags:
        - player
      summary: Add friend.
      description: This allows to add a friend to a player.
      operationId: addFriend
      parameters:
        - name: playerId
          in: path
          required: true
          schema:
            type: integer
            format: int64
        - name: friendId
          in: query
          required: true
          schema:
            type: integer
            format: int64
      #check this requestBody
      requestBody:
        description: This is the friend object.
        content:
          'application/json':
            schema:
              $ref: '#/components/schemas/player' #maybe we need to create another db

      responses:
        '201':
          description: The image has been upload.

components:
  schemas:
    players:
      type: array
      items:
        $ref: '#/components/schemas/player'

    player:
      type: object
      required:
        - username
      properties:
        playerId:
          readOnly: true
          type: integer
        username:
          type: string
        avatar:
          type: string # url image
        authentication:
          readOnly: true
          type: boolean
        friends:
          type: array
